import json
from collections.abc import Sequence
from dataclasses import dataclass
from typing import Any, cast

import pulumi
import pulumi_aws as aws
import pulumi_eks as eks
from pulumi_aws.ec2.get_subnets import get_subnets
from pulumi_aws.ec2.get_vpc import get_vpc
from pulumi_aws.rds.outputs import InstanceMasterUserSecret

DATABASE_NAME = "kiana"
DATABASE_PORT = 5432
DATABASE_USERNAME = "kiana_admin"
SERVICE_ACCOUNT_NAMESPACE = "dummy-server"
SERVICE_ACCOUNT_NAME = "dummy-server"


@dataclass(frozen=True)
class PostgresDatabase:
    """The RDS instance and the IAM identity used by dummy-server."""

    instance: aws.rds.Instance
    secret_arn: pulumi.Output[str]
    application_role: aws.iam.Role


def _tags() -> dict[str, str]:
    return {
        "Project": "kiana",
        "Environment": pulumi.get_stack(),
        "ManagedBy": "Pulumi",
    }


def _extract_secret_arn(secrets: Sequence[InstanceMasterUserSecret]) -> str:
    if len(secrets) != 1 or not secrets[0].secret_arn:
        raise ValueError("RDS did not return its managed master-user secret ARN")
    return secrets[0].secret_arn


def _build_assume_role_policy(oidc: dict[str, str]) -> str:
    issuer = oidc["issuer"]
    return json.dumps(
        {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Effect": "Allow",
                    "Principal": {"Federated": oidc["provider_arn"]},
                    "Action": "sts:AssumeRoleWithWebIdentity",
                    "Condition": {
                        "StringEquals": {
                            f"{issuer}:aud": "sts.amazonaws.com",
                            f"{issuer}:sub": (
                                "system:serviceaccount:"
                                f"{SERVICE_ACCOUNT_NAMESPACE}:{SERVICE_ACCOUNT_NAME}"
                            ),
                        }
                    },
                }
            ],
        }
    )


def _build_secret_read_policy(secret_arn: str) -> str:
    return json.dumps(
        {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Effect": "Allow",
                    "Action": "secretsmanager:GetSecretValue",
                    "Resource": secret_arn,
                }
            ],
        }
    )


def create_postgres_database(cluster: eks.Cluster) -> PostgresDatabase:
    """Create a small private PostgreSQL instance for dummy-server."""
    default_vpc = get_vpc(default=True)
    default_subnets = get_subnets(
        filters=[
            {
                "name": "vpc-id",
                "values": [default_vpc.id],
            }
        ]
    )

    subnet_group = aws.rds.SubnetGroup(
        "dummy-server",
        description="Default VPC subnets available to the Kiana PostgreSQL instance",
        subnet_ids=default_subnets.ids,
        tags=_tags(),
    )
    security_group = aws.ec2.SecurityGroup(
        "dummy-server-database",
        description="Allow PostgreSQL connections only from Kiana EKS workers",
        vpc_id=default_vpc.id,
        ingress=[
            aws.ec2.SecurityGroupIngressArgs(
                description="PostgreSQL from EKS nodes and their pods",
                from_port=DATABASE_PORT,
                to_port=DATABASE_PORT,
                protocol="tcp",
                security_groups=[cluster.node_security_group_id],
            )
        ],
        tags=_tags(),
    )
    instance = aws.rds.Instance(
        "dummy-server",
        allocated_storage=20,
        apply_immediately=True,
        auto_minor_version_upgrade=True,
        backup_retention_period=0,
        db_name=DATABASE_NAME,
        db_subnet_group_name=subnet_group.name,
        deletion_protection=False,
        engine="postgres",
        engine_lifecycle_support="open-source-rds-extended-support-disabled",
        instance_class="db.t4g.micro",
        manage_master_user_password=True,
        multi_az=False,
        port=DATABASE_PORT,
        publicly_accessible=False,
        skip_final_snapshot=True,
        storage_encrypted=True,
        storage_type="gp3",
        username=DATABASE_USERNAME,
        vpc_security_group_ids=[security_group.id],
        tags=_tags(),
    )

    # The value is generated by RDS. Pulumi receives the ARN, not the password.
    secret_arn: pulumi.Output[str] = cast(Any, instance.master_user_secrets).apply(
        _extract_secret_arn
    )
    oidc = pulumi.Output.all(
        provider_arn=cluster.oidc_provider_arn,
        issuer=cluster.oidc_issuer,
    )
    assume_role_policy: pulumi.Output[str] = cast(Any, oidc).apply(
        _build_assume_role_policy
    )
    application_role = aws.iam.Role(
        "dummy-server-database",
        assume_role_policy=assume_role_policy,
        description="Read the dummy-server RDS credential from Secrets Manager",
        tags=_tags(),
    )
    secret_read_policy: pulumi.Output[str] = cast(Any, secret_arn).apply(
        _build_secret_read_policy
    )
    aws.iam.RolePolicy(
        "dummy-server-database",
        role=application_role.name,
        policy=secret_read_policy,
    )

    return PostgresDatabase(
        instance=instance,
        secret_arn=secret_arn,
        application_role=application_role,
    )
